package models;
// Generated Nov 12, 2014 12:25:14 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Assets generated by hbm2java
 */
public class Assets  implements java.io.Serializable {


     private String id;
     private Location location;
     private Users users;
     private Date purchaseDate;
     private String description;
     private String extraInfo;
     private boolean isLendable;
     private boolean isMaterial;
     private boolean isDamaged;
     private boolean isLost;
     private Set<AssetNotes> assetNoteses = new HashSet<AssetNotes>(0);
     private Set<Lends> lendses = new HashSet<Lends>(0);
     private Set<ReportItem> reportItems = new HashSet<ReportItem>(0);

    public Assets() {
    }

	
    public Assets(String id, Date purchaseDate, boolean isLendable, boolean isMaterial, boolean isDamaged, boolean isLost) {
        this.id = id;
        this.purchaseDate = purchaseDate;
        this.isLendable = isLendable;
        this.isMaterial = isMaterial;
        this.isDamaged = isDamaged;
        this.isLost = isLost;
    }
    public Assets(String id, Location location, Users users, Date purchaseDate, String description, String extraInfo, boolean isLendable, boolean isMaterial, boolean isDamaged, boolean isLost, Set<AssetNotes> assetNoteses, Set<Lends> lendses, Set<ReportItem> reportItems) {
       this.id = id;
       this.location = location;
       this.users = users;
       this.purchaseDate = purchaseDate;
       this.description = description;
       this.extraInfo = extraInfo;
       this.isLendable = isLendable;
       this.isMaterial = isMaterial;
       this.isDamaged = isDamaged;
       this.isLost = isLost;
       this.assetNoteses = assetNoteses;
       this.lendses = lendses;
       this.reportItems = reportItems;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public Location getLocation() {
        return this.location;
    }
    
    public void setLocation(Location location) {
        this.location = location;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public Date getPurchaseDate() {
        return this.purchaseDate;
    }
    
    public void setPurchaseDate(Date purchaseDate) {
        this.purchaseDate = purchaseDate;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getExtraInfo() {
        return this.extraInfo;
    }
    
    public void setExtraInfo(String extraInfo) {
        this.extraInfo = extraInfo;
    }
    public boolean isIsLendable() {
        return this.isLendable;
    }
    
    public void setIsLendable(boolean isLendable) {
        this.isLendable = isLendable;
    }
    public boolean isIsMaterial() {
        return this.isMaterial;
    }
    
    public void setIsMaterial(boolean isMaterial) {
        this.isMaterial = isMaterial;
    }
    public boolean isIsDamaged() {
        return this.isDamaged;
    }
    
    public void setIsDamaged(boolean isDamaged) {
        this.isDamaged = isDamaged;
    }
    public boolean isIsLost() {
        return this.isLost;
    }
    
    public void setIsLost(boolean isLost) {
        this.isLost = isLost;
    }
    public Set<AssetNotes> getAssetNoteses() {
        return this.assetNoteses;
    }
    
    public void setAssetNoteses(Set<AssetNotes> assetNoteses) {
        this.assetNoteses = assetNoteses;
    }
    public Set<Lends> getLendses() {
        return this.lendses;
    }
    
    public void setLendses(Set<Lends> lendses) {
        this.lendses = lendses;
    }
    public Set<ReportItem> getReportItems() {
        return this.reportItems;
    }
    
    public void setReportItems(Set<ReportItem> reportItems) {
        this.reportItems = reportItems;
    }
}


