package models;
// Generated Nov 12, 2014 12:25:14 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Lends generated by hbm2java
 */
public class Lends  implements java.io.Serializable {


     private int id;
     private Assets assets;
     private Users users;
     private Date lendFrom;
     private Date lendTo;
     private String purpose;
     private String extraInfo;

    public Lends() {
    }

	
    public Lends(int id, Assets assets, Users users, Date lendFrom, Date lendTo, String purpose) {
        this.id = id;
        this.assets = assets;
        this.users = users;
        this.lendFrom = lendFrom;
        this.lendTo = lendTo;
        this.purpose = purpose;
    }
    public Lends(int id, Assets assets, Users users, Date lendFrom, Date lendTo, String purpose, String extraInfo) {
       this.id = id;
       this.assets = assets;
       this.users = users;
       this.lendFrom = lendFrom;
       this.lendTo = lendTo;
       this.purpose = purpose;
       this.extraInfo = extraInfo;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Assets getAssets() {
        return this.assets;
    }
    
    public void setAssets(Assets assets) {
        this.assets = assets;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public Date getLendFrom() {
        return this.lendFrom;
    }
    
    public void setLendFrom(Date lendFrom) {
        this.lendFrom = lendFrom;
    }
    public Date getLendTo() {
        return this.lendTo;
    }
    
    public void setLendTo(Date lendTo) {
        this.lendTo = lendTo;
    }
    public String getPurpose() {
        return this.purpose;
    }
    
    public void setPurpose(String purpose) {
        this.purpose = purpose;
    }
    public String getExtraInfo() {
        return this.extraInfo;
    }
    
    public void setExtraInfo(String extraInfo) {
        this.extraInfo = extraInfo;
    }




}


