package scrooge.models;
// Generated Nov 12, 2014 12:25:14 PM by Hibernate Tools 4.3.1



/**
 * ReportItem generated by hbm2java
 */
public class ReportItem  implements java.io.Serializable {


     private int id;
     private Assets assets;
     private Report report;
     private String extraInfo;
     private boolean isDamaged;
     private boolean isLost;

    public ReportItem() {
    }

	
    public ReportItem(int id, Assets assets, Report report, boolean isDamaged, boolean isLost) {
        this.id = id;
        this.assets = assets;
        this.report = report;
        this.isDamaged = isDamaged;
        this.isLost = isLost;
    }
    public ReportItem(int id, Assets assets, Report report, String extraInfo, boolean isDamaged, boolean isLost) {
       this.id = id;
       this.assets = assets;
       this.report = report;
       this.extraInfo = extraInfo;
       this.isDamaged = isDamaged;
       this.isLost = isLost;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Assets getAssets() {
        return this.assets;
    }
    
    public void setAssets(Assets assets) {
        this.assets = assets;
    }
    public Report getReport() {
        return this.report;
    }
    
    public void setReport(Report report) {
        this.report = report;
    }
    public String getExtraInfo() {
        return this.extraInfo;
    }
    
    public void setExtraInfo(String extraInfo) {
        this.extraInfo = extraInfo;
    }
    public boolean isIsDamaged() {
        return this.isDamaged;
    }
    
    public void setIsDamaged(boolean isDamaged) {
        this.isDamaged = isDamaged;
    }
    public boolean isIsLost() {
        return this.isLost;
    }
    
    public void setIsLost(boolean isLost) {
        this.isLost = isLost;
    }




}


