package scrooge.models;
// Generated Nov 12, 2014 12:25:14 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private String login;
     private String name;
     private String surname;
     private String pesel;
     private Date birthdate;
     private String password;
     private Set<Lends> lendses = new HashSet<Lends>(0);
     private Set<Assets> assetses = new HashSet<Assets>(0);
     private Set<AssetNotes> assetNoteses = new HashSet<AssetNotes>(0);
     private boolean isAdmin;

    public Users() {
    }

	
    public Users(String login, String name, String pesel, Date birthdate, String password, boolean isAdmin) {
        this.login = login;
        this.name = name;
        this.pesel = pesel;
        this.birthdate = birthdate;
        this.password = password;
        this.isAdmin = isAdmin;
    }
    public Users(String login, String name, String surname, String pesel, Date birthdate, String password, boolean isAdmin, Set<Lends> lendses, Set<Assets> assetses, Set<AssetNotes> assetNoteses) {
       this.login = login;
       this.name = name;
       this.surname = surname;
       this.pesel = pesel;
       this.birthdate = birthdate;
       this.password = password;
       this.isAdmin = isAdmin;
       this.lendses = lendses;
       this.assetses = assetses;
       this.assetNoteses = assetNoteses;
    }
   
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getSurname() {
        return this.surname;
    }
    
    public void setSurname(String surname) {
        this.surname = surname;
    }
    public String getPesel() {
        return this.pesel;
    }
    
    public void setPesel(String pesel) {
        this.pesel = pesel;
    }
    public Date getBirthdate() {
        return this.birthdate;
    }
    
    public void setBirthdate(Date birthdate) {
        this.birthdate = birthdate;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setIsAdmin(boolean isAdmin) {
        this.isAdmin = isAdmin;
    }
    public boolean getIsAdmin() {
        return this.isAdmin;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Set<Lends> getLendses() {
        return this.lendses;
    }
    
    public void setLendses(Set<Lends> lendses) {
        this.lendses = lendses;
    }
    public Set<Assets> getAssetses() {
        return this.assetses;
    }
    
    public void setAssetses(Set<Assets> assetses) {
        this.assetses = assetses;
    }
    public Set<AssetNotes> getAssetNoteses() {
        return this.assetNoteses;
    }
    
    public void setAssetNoteses(Set<AssetNotes> assetNoteses) {
        this.assetNoteses = assetNoteses;
    }




}


